### ISSUE TITLE
Roadmap to version 1.0 missing

### ISSUE THREAD

**Issue by arnabanimesh** [tokio-rs/axum#1008]
### Motivation

I want to know if I can use `axum` in production now, or if not now then when

### Proposal

A roadmap as to when the `1.0` version will be released or the library is production ready. If there will be no **major** breaking changes even before `1.0` release, I would like to know when.

**Comment by davidpdrsn** [comment]
axum is absolutely production ready! Version numbers and production readiness are two entirely different things.

We don't have a plan for when we release new major versions. It depends on the changes we'd like to make and how long ago we shipped the current major version.

axum wont be 1.0 for a while, at least not before all our public dependencies are also 1.0. I also see little need for a roadmap since 1.0 isn't something we're actively working towards. axum is less than a year old so breaking changes will absolutely happen in the future.
