### ISSUE TITLE
Adding nested fallbacks is harder than it should be

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#1053]
We currently don't support nesting routers that have fallbacks. This panics:

```rust
let api_routes = Router::new()
    .route("/v1/foo", get(|| async {}))
    .fallback((|| async { "api fallback" }).into_service());

let app = Router::new()
    .nest("/api", api_routes)
    .fallback((|| async { "general fallback" }).into_service());
```

This is because while `Router::nest` takes `T: Service` it attempts to downcast that into a `Router`. If that succeeds it takes a different code path that simply moves routes from one router to another while adding the prefix. However that means we cannot have two `fallbacks` since we only have one `Router` in the end.

A possible workaround is to use another `Router` as a fallback:

```rust
let api_routes = Router::new()
    .route("/v1/foo", get(|| async {}));

let app = Router::new()
    .nest("/api", api_routes)
    .fallback(
        Router::new()
            .nest("/api", (|| async { "api fallback" }).into_service())
            .fallback((|| async { "general fallback" }).into_service()),
    );
```

While this works its not very obvious and it would be great if multiple nested fallbacks just worked.

Haven't thought through how to make it work but I believe it requires https://github.com/ibraheemdev/matchit/issues/18

**Comment by lilyball** [comment]
In the short term, I believe that simply treating the nested router as an opaque service in the case where it has a fallback would work. You cannot currently add a nested router that has a fallback, so that approach can't possibly break any code. This would only need to be done if the nested router actually has a fallback, otherwise the current behavior is fine.

**Comment by davidpdrsn** [comment]
That's a good idea actually 🤔 might get us most of the way there.

**Comment by lilyball** [comment]
I don't know what the expected time frame for https://github.com/ibraheemdev/matchit/issues/18 is. If it will be a while, another potential workaround would be to detect the nested router w/fallback, don't merge it, but do convert all of its own routes to be wrapped in `StripPrefix` (instead of wrapping the whole router with that). Then `route_layer` itself could detect that the service for the nested route is a `Router` and call `route_layer` on that nested `Router` instead of applying the layer around it (like how it does for `Endpoint::MethodRouter`).

If I correctly understand the way this works, that would have a similar effect to merging the nested router with ibraheemdev/matchit#18 fixed, and since it's pushing the `StripPrefix` out to the nested routes that would preserve the full path for route layers.

**Comment by davidpdrsn** [comment]
This is blocked by https://github.com/tokio-rs/axum/pull/1086

**Comment by davidpdrsn** [comment]
I just opened https://github.com/tokio-rs/axum/pull/1161 which should fix this. @lilyball Do you wanna try and test it?

**Comment by davidpdrsn** [comment]
I've decided not to support this its not worth the additional complexity it adds. See https://github.com/tokio-rs/axum/pull/1086#issuecomment-1195323750.

**Comment by jplatte** [comment]
Suggested solution (extended for clarity) so people don't have to click around:

```rust
fn router() -> Router {
    Router::new().fallback(...)
}

fn make_some_routes() -> Router {
    router().route("/", ...)
}

fn make_more_routes() -> Router {
    router().route("/", ...)
}

fn my_routes() -> Router {
    router()
        .nest("/a", make_some_routes())
        .nest("/b", make_more_routes())
}
```

**Comment by lilyball** [comment]
If this is really the solution we're going with then please make sure any documentation recommending this explicitly recommends using `OriginalUri` in the fallback, as copying the fallback onto the nested router will potentially break any fallbacks that are just using the request URI.
