### ISSUE TITLE
spa router response should have etag

### ISSUE THREAD

**Issue by thegenius** [tokio-rs/axum#1237]
### Motivation

when use spa router to serve static files, etag will improve the performance.

**Comment by davidpdrsn** [comment]
`SpaRouter` is a thin wrapper around `ServeDir` which already sets `Last-Modified` and checks `If-Modified-Since` which serves a similar purpose. The advantage of using those headers, instead of `E-Tag`, is that we don't need to read the file into memory and compute a hash.

Feel free to open an issue on tower-http if you have more questions but I'll close this for now since there is nothing we can do about this in axum.
