### ISSUE TITLE
Order of calls is important for registering routes

### ISSUE THREAD

**Issue by sazzer** [tokio-rs/axum#1341]
### Motivation

I've just spent far too long trying to fix an issue that was caused by the fact that this:
```
    Router::new()
        .layer(Extension(users_service))
        .route("/users/:id", axum::routing::get(get::handler))
```

is not the same as this:
```
    Router::new()
        .route("/users/:id", axum::routing::get(get::handler))
        .layer(Extension(users_service))
```

Naively it seems that it shouldn't make any difference, or even that the first one is *more* correct, but in actual fact, the second one is the way that you're required to do it or else it doesn't work.

### Proposal

Ideally, having the two options be equivalent would make things less error-prone.

### Alternatives

As an alternative, having something that actually indicates that I've been an idiot and wired it up wrong would at least have saved me some time :)

**Comment by sazzer** [comment]
I should say btw that I'm aware the documentation for `Router::layer` already states what you're meant to do. It's just that I'd missed that, got it wrong and nothing was shouting at me that I'd made this mistake. It seems that it would be reasonable to either log or panic if you add middleware to a router with zero routes, since in that case the middleware isn't going to affect anything and is therefore redundant.

**Comment by jplatte** [comment]
We recently did this to `route_layer` because there it's truly a no-op. For `layer` it's not actually a true no-op, since the middleware will run on the default fallback handler.

Logging a warning might be one solution, though in the extremely unlikely case you actually wanted this, maybe it's kinda unfortunate? Also it's not quite as obvious as a panic.

**Comment by sazzer** [comment]
The whole thing with the fallback handlers isn't something I'd realised, and really makes this an impossible ask because suddenly there are good reasons why someone would want to do the thing that I did my mistake...

**Comment by davidpdrsn** [comment]
I think I'll close this.

I'm sympathetic to the argument that the order of `route` and `fallback` doesn't matter so therefore the order of `layer` (and `route_layer`) shouldn't matter either. However that isn't possible since we need to run multiple middleware so ones gotta run before another. For routes we always find one and run only that. So we do have to pick _an ordering_ and I think the current way it works makes sense.
