### ISSUE TITLE
Middleware links in docs page don't work

### ISSUE THREAD

**Issue by frederikhors** [tokio-rs/axum#1386]
Middleware links at [this docs page](https://docs.rs/axum/latest/axum/middleware/index.html#commonly-used-middleware) don't work:

![image](https://user-images.githubusercontent.com/41120635/190901514-d02344e1-8099-4bb3-895e-f3cdac8d103a.png)

![image](https://user-images.githubusercontent.com/41120635/190901538-71582a9f-e022-4404-9a2a-475e5f524106.png)

**Comment by davidpdrsn** [comment]
It's fixed in 0.6: https://docs.rs/axum/0.6.0-rc.2/axum/middleware/index.html#commonly-used-middleware

Don't think this needs to be backported.

**Comment by LauH1987** [comment]
I don't know if this is a docs.rs issue, but three of the links in the docs middleware link to "crate::middleware::*" instead of the relevant url (ie. https://docs.rs/axum/latest/axum/middleware/fn.from_fn.html). I could _not_ recreate this when building the docs locally.
![image](https://user-images.githubusercontent.com/22587888/227127669-3b01211e-7860-4b93-8b63-5612ac246cc6.png)

**Comment by davidpdrsn** [comment]
@LauH1987 good catch! But please open a new issue as it's a different thing.
