### ISSUE TITLE
Reuse the code of `Extract` when implementing `Service`.

### ISSUE THREAD

**Issue by sunli829** [tokio-rs/axum#147]
### Motivation

I want to implement a `Service` for GraphQL query execution so as to avoid boilerplate code like the following.

https://github.com/async-graphql/examples/blob/7e3304e406adaff8d28a025becd91867ecae199a/axum/starwars/src/main.rs#L8

I have implemented a [GraphQL request extractor](https://github.com/async-graphql/async-graphql/blob/9a76ea9896b569e5b3cf88a39fdf80b267cf8efa/integrations/axum/src/extract.rs#L46), I want to implement `Service` can reuse it.

But I cannot use `RequestParts::new` because it is `pub(crate)`, so should we change to `pub`?
Or there is a better solution, please tell me. 🙂

**Comment by davidpdrsn** [comment]
I think we could look into making `RequestParts` usable outside axum.

Would have to think a bit more about the design however. `new` is pretty straight forward but I imagine users would want `into_request` as well. That is currently not very idiomatic since it takes `&mut self` (`into_*` methods normally take `self`) and panics if the request body has been extracted (to avoid requiring `B: Default` which might be problematic).

Or maybe there is a totally different way of making extractors usable from services that don't require these bits being public 🤔

If you wanna ship something in `async-graphql`, and don't want to wait for this, I would probably recommend writing a service without using an extractor for axum.

**Comment by davidpdrsn** [comment]
I was able to clean up the API of `RequestParts` in https://github.com/tokio-rs/axum/pull/167. I think we could consider exposing the API as it is now.

**Comment by sunli829** [comment]
So we only need to change `pub(crate)` to `pub` now? 🙂

**Comment by davidpdrsn** [comment]
Pretty much 😅 I still wanna do some experimentation and see what its actually like to use.

**Comment by davidpdrsn** [comment]
I've been thinking about this and actually think its fine to make the methods `pub`. Just requires writing some docs.
