### ISSUE TITLE
Merge nested router with same base path cause panic

### ISSUE THREAD

**Issue by BratSinot** [tokio-rs/axum#1601]
### Version

```
├── axum v0.6.1
│   ├── axum-core v0.3.0
```

### Platform

```
Linux BratSinot 5.19.17 #1 SMP PREEMPT_DYNAMIC Mon Oct 24 13:00:29 CDT 2022 x86_64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz GenuineIntel GNU/Linux
```

### Description

Merge nested routes with same "base" path cause panic at runtime:
```rust
use axum::{
    routing::{get, post},
    Router,
};

fn main() {
    /* these are configurable */
    let base_path = "/";
    let get_base_path = "/";
    let post_base_path = "/";

    let get_route = Router::new().nest(
        get_base_path,
        Router::new().route("/get", get(|| std::future::ready("Ho".to_owned()))),
    );
    let post_route = Router::new().nest(
        post_base_path,
        Router::new().route("/post", post(|| std::future::ready("Ho".to_owned()))),
    );
    let app: Router<String> =
        Router::new().nest(base_path, Router::new().merge(get_route).merge(post_route));
}
```
and got error:
```log
thread 'main' panicked at 'Invalid route "/": insertion failed due to conflict with previously registered route: /*__private__axum_nest_tail_param', src/main.rs:21:70
stack backtrace:
```

The idea is to give user abbility to customise paths:
```
├── <base_path> -> root_handler
│   ├── /<second_base>/second -> second_handler
...
│   ├── /<Nth_base>/second -> Nth_handler
```

**Comment by davidpdrsn** [comment]
The minimal version of what you're asking for is

```rust
let _: Router = Router::new()
    .nest("/", Router::new().route("/", get(...)))
    .nest("/", Router::new().route("/", post(...)));
```

which isn't supported.

The reason is that axum nests services (which includes `Router`s) as "opaque services", i.e. an `impl Service<Request>`. All requests with a matching prefix will then be sent to that service.

axum has no idea what the service actually is. It could be a `Router` but it could also be a [`ServeDir`](https://docs.rs/tower-http/latest/tower_http/services/struct.ServeDir.html) and because of this axum cannot merge the routes when you're nesting two routers at the same path. `Service` has no concept of "routes".

In 0.5 axum supported this through [dirty hacks](https://github.com/tokio-rs/axum/blob/0.5.x/axum/src/routing/mod.rs#L209) which introduced a lot inconsistencies and edge cases. So for 0.6 that was simplified so nesting `Router`s and general services work the same. The cost of that change is that what you're trying do to isn't possible.

So you'll have to find some other way of doing it. Perhaps using `Router::merge` and setting the prefixes on the routes yourself.
