### ISSUE TITLE
Unable to set Cookie max_age

### ISSUE THREAD

**Issue by barvirm** [tokio-rs/axum#1881]
## Feature Request
I want to reexport the time "sub crate" of the Cookie crate to be able to set max_age without adding a new dependency.

### Motivation
If you want to see max_age, you need to add a new dependency, time, or Cookie crate to be able to use `time::Duration`.
### Proposal
Reexport time subcrate from Cookie.

**Comment by davidpdrsn** [comment]
I don't think re-exporting a dependency of a dependency is right. You can just depend on time yourself.

**Comment by jplatte** [comment]
Sure, I guess. Feel free to send a PR adding a re-export of `Duration` to `axum_extra::extract::cookie`.

**Comment by Darckfast** [comment]
is the https://github.com/rwf2/cookie-rs used for any particular reason? 

im asking because i was looking into the `time` crate issue https://github.com/rwf2/cookie-rs/issues/109 when using `max_age`, and i was asking myself if it woudn't be easier to switch to a cookie crate that implements the same basic functionality using only `std` libs, instead of having do these hoops
