### ISSUE TITLE
Add support for reqwest's Response to axum's Response

### ISSUE THREAD

**Issue by baoyachi** [tokio-rs/axum#2008]
How to Convert the Response of [reqwest](https://docs.rs/reqwest/latest/reqwest/struct.Response.html#) to the Response of [axum](https://docs.rs/axum/latest/axum/response/trait.IntoResponse.html)

**Comment by davidpdrsn** [comment]
I don't think it's appropriate for axum-core to depend on reqwest (even optionally). I think a better solution is to add a method like

```rust
impl reqwest::Response {
    fn into_http(self) -> http::Response<?> { ... }
}
```

for converting the `reqwest::Response` into an `http::Response`. This method needs to into `reqwest`. Can't add it from the outside.

Since [`http::Response` implements `IntoResponse`](https://docs.rs/axum-core/latest/axum_core/response/trait.IntoResponse.html#impl-IntoResponse-for-Response%3CB%3E) it would work with axum out of the box.

**Comment by jplatte** [comment]
There's a feature request for that here by the way: https://github.com/seanmonstar/reqwest/issues/1258
It's the only conversion between reqwest's and http's request / response types that's still missing.
