### ISSUE TITLE
Remove Hyper from axum's public API

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/axum#205]
## Feature Request

Similar to #186

### Motivation

Currently, Hyper types are used in a few places. This requires the user to include a dependency on `hyper` to get started and also results in the user bouncing between `axum` and `hyper` when reading API docs.

### Proposal

Remove hyper from axum's public API by providing its own types and wrapping hyper's.

There may be more, but the main types are:

* `Body`
* `Server`

For `Body`, axum should provide its own `struct Body` that internally can be multiple possible representations, including a hyper body. For `Server`, `axum` should provide its own `Server` type that decorates the hyper server and provides a simpler API, especially with regards to trait bounds.

There could also be a `.serve(...)` function that is called after building the app.

**Comment by jplatte** [comment]
`axum` already re-exports both `Body` and `Server` (though it seems the former is not shown as being a re-export in the docs), so one doesn't actually have to depend directly on hyper, or switch back and forth between docs.

**Comment by carllerche** [comment]
> `axum` already re-exports both `Body` and `Server` (though it seems the former is not shown as being a re-export in the docs), so one doesn't actually have to depend directly on hyper, or switch back and forth between docs.

You are correct, it is primarily an API doc experience. re-exports don't show up when searching for types and once you go to the re-export API docs, the examples are no longer focused on `axum`. Also, I hope that `axum`'s `serve` fn would have simpler trait bounds than [hyper's](https://docs.rs/hyper/0.14.11/hyper/server/struct.Builder.html#method.serve)

**Comment by KaiJewson** [comment]
I think a better solution for `Body` would be to add `body::{AsyncRead, Stream, Channel}` as separate types, since that's the direction Hyper's `Body` is going in as well. That would also allow renaming `body::HttpBody` to just `body::Body`.

Regarding the `Server` type, there's also the option of Axum not exposing _any_ kind of way to create a server - that way, it would just be a small library for routing requests rather than a web framework. This doesn't solve the problem of the `hyper` dependency or having to bounce back and forth between API docs, but IMO the more clear separation between the two libraries makes it OK. I think there is definitely room here for a library that builds a high-level API on top of Hyper (providing TLS, simpler trait bounds, and eventually a `Server` type once Hyper has removed that API) and that library could be easily paired with Axum.

**Comment by davidpdrsn** [comment]
> I think a better solution for `Body` would be to add `body::{AsyncRead, Stream, Channel}` as separate types, since that's the direction Hyper's `Body` is going in as well. That would also allow renaming `body::HttpBody` to just `body::Body`.

I agree with this. Ideally I think such body types should live in `http_body` and not axum or hyper. But I'm fine with iterating on things in axum with the eventual goal of moving them out of axum. I like the flexiblity it brings. Someone might need a "channel body" without wanting hyper.

There might be some potential UX issues in having multiple body types to pick between rather than picking a method on `hyper::Body`. Could perhaps be solved with good docs on the `axum::body` module.

> Regarding the Server type, there's also the option of Axum not exposing any kind of way to create a server - that way, it would just be a small library for routing requests rather than a web framework.

I think this hits the nail on the head: how big should axum be? Whats the scope?

So far my goal for axum has been to to focus on 1) embracing `tower::Service` for routing and middleware 2) extracting data from requests and 3) generating responses. This is why axum doesn't have a built-in `Server` today, because I consider it out of scope.

Additionally, I personally like that someone else (hyper) gets to deal with all the server related issues like [configuration](https://docs.rs/hyper/0.14.11/hyper/server/struct.Builder.html) and TLS. That allows axum to focus on the three pillars mentioned before. warp currently has [9 TLS related issues](https://github.com/seanmonstar/warp/issues?q=is%3Aissue+is%3Aopen+tls) open. I'm a bit afraid that if we start going down the `axum::Server` route that we'll end up in a similar situation. The general advice could of course simply be "we wont support this, go directly to hyper".

The one issue I do have with `hyper::Server` today is the trait bounds on [`serve`](https://docs.rs/hyper/0.14.11/hyper/server/struct.Builder.html#method.serve). They make type errors look much worse than they often are. This definitely is a real issue. Maybe we could get most of the way there by simply providing this

```rust
async fn serve<S>(addr: SocketAddr, svc: S) -> Result<(), axum::Error>
where
    S: Service<Request<hyper::Body>, Response = Response<axum::body::BoxBody>> + Clone + Send + 'static,
    S::Error: Into<Box<dyn std::error::Error + Send + Sync>>,
    S::Future: Send,
{
    hyper::Server::bind(&addr)
        .serve(tower::make::Shared::new(svc))
        .await
        .map_err(axum::Error::new)
}
```

Thats the minimal set of bounds you can get away with.

I think my dream scenario would be

- Hyper promotes the low level API as the main API, as described here https://github.com/hyperium/hyper/issues/2321
- The current high level parts of hyper are extracted into a separate crate that uses tower, http, http_body as the core abstraction. This crate would embrace its high level nature and focus on providing good error messages and related DX things. It makes setting up TLS easy.
- Axum doesn't include its own server but instead allows you to pick between the more low level hyper, or the new higher level server crate.

**Comment by davidpdrsn** [comment]
I think we should punt on this for 0.2. Would like to get 0.2 out next week and don't think this a major issue that can't wait until 0.3.

**Comment by davidpdrsn** [comment]
I think this will be part of a larger discussion around what hyper 1.0 will look like but I think I'll kick the can down the road for now and close this.
