### ISSUE TITLE
Documentation outdated for accessing inner errors

### ISSUE THREAD

**Issue by giarc3** [tokio-rs/axum#2077]
- [x] I have looked for existing issues (including closed) about this

### Description

In v0.6.0, the inner error of a `JsonRejection` changed from `serde_json::Error` to `serde_path_to_error::Error<serde_json::Error>`. However, the documentation example for [Accessing inner errors](https://github.com/tokio-rs/axum/blob/main/axum/src/docs/extract.md?plain=1#L357) still shows calling `find_error_source` with `serde_json::Error`, which will not succeed.

**Comment by davidpdrsn** [comment]
I assumed that since `serde_path_to_error::Error` [returns the original's source in its `Error` impl](https://docs.rs/serde_path_to_error/latest/src/serde_path_to_error/lib.rs.html#120-122) it would work but I just did some testing and yeah indeed it's broken. Thats curious 🤔 Do you know why it doesn't work?

**Comment by giarc3** [comment]
> Do you know why it doesn't work? 

I don't; it surprised me as well

**Comment by giarc3** [comment]
After looking at it more, I expect it's just because of what you linked. The `err` itself is a `serde_path_to_error::Error<serde_json::Error>`, so it will fail the first `err.downcast_ref`'s `self.is::<serde_json::Error>` check, and then call `find_error_source` on the `err.source()`. And instead of that returning the `original` (a `serde_json::Error`), it instead return's the `original`'s source, effectively skipping over the `serde_json::Error`.
