### ISSUE TITLE
Support Http3 Webtransport

### ISSUE THREAD

**Issue by athxx** [tokio-rs/axum#2088]
- [X] I have looked for existing issues (including closed) about this

## Feature Request

Support h3 webtransport

### Motivation

I have noticed that hyper v1.0.0-rc.4 has recently been released, indicating that the h3 protocol is nearing stability. Given this development, I believe it would be beneficial for the Axum project to support WebTransport, which utilizes the h3 protocol.

### Proposal

I propose adding support for WebTransport to the axum project. This would involve implementing the necessary functionality to establish WebTransport connections and handle WebTransport streams. By incorporating WebTransport support, axum can provide its users with a more comprehensive and modern networking solution.

### Alternatives

One potential alternative is to rely on existing protocols such as HTTP/2 or WebSocket for similar functionality. However, WebTransport offers certain advantages over these protocols, including reduced latency and improved efficiency for low-latency applications. By embracing WebTransport, axum can keep pace with the latest advancements in web networking technology and provide enhanced performance for its users.

**Comment by davidpdrsn** [comment]
If hyper supports h3 then webtransport would be great to support as well. However I don't think an implementation will depend on any private internals of axum and thus doesn't need to be built in and could be in a separate crate.

WebSocket really doesn't need to be built in either but we include it because it's so common. [`axum-tungstenite`](https://crates.io/crates/axum-tungstenite) is another crate I maintain that does WebSockets for axum with a different API.

So my recommendation is to implement things in a separate crate and once that's mature we can consider folding it into axum.

I'll close this issue for now but feel free to ask follow up questions.

**Comment by hongbo-miao** [comment]
FWIW, the ticket on Hyper side is at https://github.com/hyperium/hyper/issues/1818
Hopefully Hyper can support it soon! ☺️
