### ISSUE TITLE
TCP reset when http body is large when using middleware 

### ISSUE THREAD

**Issue by avalon1610** [tokio-rs/axum#2168]
- [x] I have looked for existing issues (including closed) about this

### Version

axum v0.6.20
axum-core v0.3.4

### Platform

Ubuntu 20.04 (WSL) x86_64

### Description

I tried use middleware in axum, it works find when http body is small, but got TCP connection reset (wireshark) by server when client sent request with large body. 
> eg. use postman to send a binary file with size > 100M.

```rust
#[tokio::main]
async fn main() {
    let app = Router::new()
        .route("/", post(test))
        .layer(DefaultBodyLimit::disable())
        .layer(middleware::from_fn(check));
    let addr = SocketAddr::from(([0, 0, 0, 0], 5000));
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

async fn check<B>(request: Request<B>, next: Next<B>) -> Response {
    if request.headers().get("Authorization").is_none() {
        (StatusCode::UNAUTHORIZED, [("WWW-Authenticate", "Basic"); 1]).into_response()
    } else {
        next.run(request).await
    }
}

async fn test() -> impl IntoResponse {
    "ok"
}
```

**Comment by davidpdrsn** [comment]
This is unlikely to be axum's fault since it delegates all transport stuff to hyper. Are you able to reproduce it by using hyper directly?

**Comment by avalon1610** [comment]
oh yes, it can be reproduce in hyper's basic server example
```rust
use std::convert::Infallible;
use std::net::SocketAddr;
use hyper::{Body, Request, Response, Server};
use hyper::service::{make_service_fn, service_fn};

async fn handle(_req: Request<Body>) -> Result<Response<Body>, Infallible> {
    Ok(Response::new(Body::from("Hello World")))
}

#[tokio::main]
async fn main() {
    // Construct our SocketAddr to listen on...
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));

    // And a MakeService to handle each connection...
    let make_service = make_service_fn(|_conn| async {
        Ok::<_, Infallible>(service_fn(handle))
    });

    // Then bind and serve...
    let server = Server::bind(&addr).serve(make_service);

    // And run forever...
    if let Err(e) = server.await {
        eprintln!("server error: {}", e);
    }
}
```
![image](https://github.com/tokio-rs/axum/assets/1224335/bd3fe59d-cbfd-4dac-8890-9e9950075fd4)
![image](https://github.com/tokio-rs/axum/assets/1224335/ef60ed02-6f20-4389-b7e7-49269e6ccb04)

**Comment by davidpdrsn** [comment]
In that case it's not an axum bug. Please open an issue on the hyper repo instead.

**Comment by jryio** [comment]
For any one landing on this issue: The crux of it is explained well in https://github.com/hyperium/hyper/issues/2384. TL;DR

0. You decide to short circuit inside your Axum HTTP handler, maybe some header is missing from the client, they are not authorized, or something else requires you to immediately reply with some HTTP header and a empty/full body.
1. Hyper notices that the `Body` is dropped and was never streamed. In my case it is a `Multipart` (for large file uplaods)
2. Hyper buffers your short circuited request (all good), but closes the TCP connection to the client because the Body was dropped without being read (the problem).
> Since there is data that hasn't been read in the kernel buffer, that will trigger sending a TCP RST.

Your solution is to follow @avalon1610 and drain the body yourself before sending back your short circuited response.

This is slightly frustrating but it seems to be the only workaround at the moment.

If you happen to be using `Multipart` like me, you would want to do this:

```rust
fn handle_post_file(mut multipart: Multipart) -> Result<impl IntoResponse, MultipartError>{
    // FAILS to return HTTP 400, "connection reset", or in dev tools on macOS: `NS_ERROR_NET_RESET`
    return Ok((StatusCode::BAD_REQUEST, "This will never make it to the client"));

    // SUCCEEDS in returning HTTP 400
    //
    // Drains the Body so Hyper knows it has been used. When multipart is dropped now,
    // the connection will **not** be reset and we will return HTTP 400
    while let Ok(Some(_)) = multipart.next_field().await {};
    return Ok((StatusCode::BAD_REQUEST, "short circuit" ))

    // Happy Path Multipart Handling Below...
    while let Some(x) = multipart.next_file.await? {
        // You can short circuit here without resetting the connection
        return Ok((StatusCode::BAD_REQUEST, "short circuit" }}))
    }
}
```
