### ISSUE TITLE
Graceful shutdown with hyper 1.0

### ISSUE THREAD

**Issue by harryzcy** [tokio-rs/axum#2323]
- [x] I have looked for existing issues (including closed) about this

### Motivation

`with_graceful_shutdown` has been removed in hyper 1.0, not there's no convenient way to do this with `axum::serve`.

### Proposal

Adds a `with_graceful_shutdown` to axum.

### Alternatives

Provide an example to use `hyper` connections directly: https://github.com/hyperium/hyper/pull/3303

**Comment by davidpdrsn** [comment]
This is something that should go in https://github.com/hyperium/hyper-util and not axum. axum doesn't know anything about the underlying transport layer so it can't implement graceful shutdown.

Have a look through [hyper's issues](https://github.com/hyperium/hyper). There might already be one, otherwise you can file a new one.

Note that axum doesn't yet support hyper 1.0 at all.

**Comment by harryzcy** [comment]
I'm tracking https://github.com/tokio-rs/axum/pull/1882. As `hyper::Server` is removed, `axum::serve(listener, service)` function confuses me and I initially thought the new API would provide a few more options.

> This is something that should go in https://github.com/hyperium/hyper-util and not axum.

That would make sense, thanks.

**Comment by davidpdrsn** [comment]
> axum::serve(listener, service) function confuses me and I initially thought the new API would provide a few more options.

The purpose of `axum::serve` is to get you going quickly. Not to provide lots of configurations. That belongs in hyper-util so it can be used by other libraries (such as tonic)
