### ISSUE TITLE
Example in `MethodRouter::layer` documentation doesn't work

### ISSUE THREAD

**Issue by jorendorff** [tokio-rs/axum#2582]
[The docs for `MethodRouter::layer`](https://docs.rs/axum/latest/axum/routing/method_routing/struct.MethodRouter.html#method.layer) contain this example:

```rust
use axum::{routing::get, Router};
use tower::limit::ConcurrencyLimitLayer;

async fn handler() {}

let app = Router::new().route(
    "/",
    // All requests to `GET /` will be sent through `ConcurrencyLimitLayer`
    get(handler).layer(ConcurrencyLimitLayer::new(64)),
);
```

This compiles, but no concurrency limit is enforced. This is because each request to `GET /` is sent through a different `ConcurrencyLimit` instance, each with its own semaphore.

Full runnable example (test with `hey -n 50 http://localhost:3000/api/test`):

```rust
use axum::{routing::get, Router};
use std::time::Duration;
use tower::limit::ConcurrencyLimitLayer;

async fn handler() {
    eprintln!("/api/test in");
    tokio::time::sleep(Duration::from_secs(1)).await;
    eprintln!("/api/test out");
}

#[tokio::main]
async fn main() {
    let app = Router::new().route(
        "/api/test",
        get(handler).layer(ConcurrencyLimitLayer::new(5)),
    );

    // run our app with hyper, listening globally on port 3000
    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    axum::serve(listener, app).await.unwrap();
}
```

**Comment by xuorig** [comment]
Maybe more context: I believe this happens because the layer gets cloned and `layer` is called on every request https://github.com/tokio-rs/axum/blob/62324aad912f17059c0952bea5989d27f05a96b3/axum/src/routing/method_routing.rs#L891

More precisely it happens here when `into_route` is called on the handler https://github.com/tokio-rs/axum/blob/62324aad912f17059c0952bea5989d27f05a96b3/axum/src/routing/method_routing.rs#L1041

The fix here is to use `GlobalConcurrencyLimitLayer` which, hands out services that share the same `Arc<Semaphore>`

```rust
 let app = Router::new()
        .route("/api/test", get(|| async move { sleep(Duration::from_millis(1000)).await; println!("API called"); format!("API /api/test called") }))
        .layer(GlobalConcurrencyLimitLayer::new(5));
```

Interestingly this seems to work with `axum 0.6`, unclear on what changed, but most likely the `layer` happened once vs on every request?

**Comment by davidpdrsn** [comment]
Oh thanks for noticing! I'm actually surprised its not working. I would have expected https://github.com/tokio-rs/axum/pull/2483 to fix it since we no longer clone the router for each request, which we used to in 0.7 until 07.4.

I did some testing and adding `.with_state(());` at the end of the router fixes it:

```rust
#[tokio::main]
async fn main() {
    let app = Router::new()
        .route(
            "/api/test",
            get(handler).layer(ConcurrencyLimitLayer::new(2)),
        )
        .with_state(()); // <-- ADD THIS

    // run our app with hyper, listening globally on port 3000
    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    axum::serve(listener, app).await.unwrap();
}
```

I'm not totally sure why that is but I'll do some more digging.
