### ISSUE TITLE
How can I set `max_concurrent_streams`

### ISSUE THREAD

**Issue by shenghui0779** [tokio-rs/axum#2864]
- [ ] I have looked for existing issues (including closed) about this

**Comment by jplatte** [comment]
Please use the [Q&A section](https://github.com/tokio-rs/axum/discussions/categories/q-a) for questions. Issues are for bug reports and feature requests. Also when creating a post there, please elaborate a little bit on what you are looking to do, just the title of this issue is not clear to me on its own.
