### ISSUE TITLE
`handler::any` only matches on known HTTP methods

### ISSUE THREAD

**Issue by twillingham** [tokio-rs/axum#289]
## Bug Report

When using the `handler::any` filter, it seems to only match on known HTTP verbs / methods that are supported by axum's `routing::MethodFilter` enum. This limits the ability of an application to support less-common verbs, such as those required by WebDAV (PROPFIND, MKCOL, etc.).

### Version

axum 0.2.3

### Platform

FreeBSD 13.0-RELEASE-P3, amd64

### Description

A sample axum implementation using any is available at https://github.com/twillingham/any-support. 

Using curl against this server, standard `curl -X GET http://localhost:3030/ -kvs` will return a 200 status code as expected, however `curl -X PROPFIND http://localhost:3030/ -kvs` will return `405 Method Not Allowed`.

**Comment by davidpdrsn** [comment]
Small clarification:

> This limits the ability of an application to support less-common verbs, such as those required by WebDAV (PROPFIND, MKCOL, etc.).

Its true that `any` doesn't work, but one can still use `route("/foo", handler.into_service())` from [`Handler::into_service`](https://docs.rs/axum/0.2.3/axum/handler/trait.Handler.html#method.into_service).

Honestly I think we should remove `handler::any` since its redundant. `service::any` is still useful since it maps the response body to `BoxBody` which makes it easier to route to arbitrary services. That isn't necessary for handlers (async functions).

What I think we should do:
- Fix `handler::any` and `service::any` so they match any method
- Deprecate `handler::any` and remove it in 0.3

Thoughts?

**Comment by twillingham** [comment]
Sounds fair enough, so long as there is a way to accomplish it!
