### ISSUE TITLE
make it easier to get from State to Extension

### ISSUE THREAD

**Issue by lolbinarycat** [tokio-rs/axum#2917]
[`Router::with_state`](https://docs.rs/axum/latest/axum/routing/struct.Router.html#method.with_state) mentions `Extension` as an alternative to `State`, but only after scrolling past 4 examples.  [`extract::State`](https://docs.rs/axum/latest/axum/extract/struct.State.html) doesn't mention `Extension` at all.

extensions are more modular, as they can be added to various handlers while keeping other handlers pure.

**Comment by Lachstec** [comment]
Hi there! If I understand you correctly, you think it would be nice to mention the concept of `Extension` way earlier in the docs so that people reading it are made aware of their existence, as they can be a more suitable solution to their problem as relying on `State`?

I also think that the docs could be improved in that regard and would take a shot at it.

**Comment by lolbinarycat** [comment]
yep, that is correct!

**Comment by Lachstec** [comment]
I openend a PR, would love your Feedback. It's just what first came to my mind and can surely be improved further.
