### ISSUE TITLE
compile error with !Send  handler shows none useful clue

### ISSUE THREAD

**Issue by mineralres** [tokio-rs/axum#299]
### Version
0.23

### Platform
Linux dev01 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Description
I have a minimal reproduction ,
https://github.com/mineralres/axum/tree/share-state-test (branch: share-state-test)
cd  examples/error-handling-and-dependency-injection
cargo build 
get the next comile error

![1630457964(1)](https://user-images.githubusercontent.com/4149781/131594868-c3a191ff-657f-4b58-aad4-e405a09ece32.jpg)

**Comment by mineralres** [comment]
change sync::Mutex to tokio::sync::Mutex will fix the problem, maybe because std::sync::Mutex is not Send

**Comment by mineralres** [comment]
I have update the code:
1. replace std::sync::Mutex to tokio::sync::Mutex will fix the first problem.
2. import redis crate, and build a struct DbTest with conn, then call the DbTest.test().await, will get the same compile error as above, so i can't get any clue from the compile error , and have to split and comment some piece of the code to "find" the problem

**Comment by davidpdrsn** [comment]
axum does not allow `!Send` futures in handlers. If we were allow to that none of the futures axum creates internally would be `Send` meaning tokio's multithreaded runtime couldn't move them around.

[From the tokio docs on `Mutex`:](https://docs.rs/tokio/1.11.0/tokio/sync/struct.Mutex.html#which-kind-of-mutex-should-you-use)

> Note that, although the compiler will not prevent the std Mutex from holding its guard across .await points in situations where the task is not movable between threads, this virtually never leads to correct concurrent code in practice as it can easily lead to deadlocks.

But tbh I haven't benchmarked or investigated this further as I didn't consider it much of an issue, although a few asked about it. I think the general recommendation is to use a non-async mutex if you're not doing IO while holding the lock otherwise use [an actor](https://ryhl.io/blog/actors-with-tokio) to coordinate access.

And yes the type error is very very bad 😞 Unfortunately there is nothing we can do in axum to improve that. The machinery that makes variadic handler functions work really hurts the error messages.

**Comment by mineralres** [comment]
At least,hope there is any method to get the clear type compil error output, otherwise it's too hard for axum beginners!

**Comment by davidpdrsn** [comment]
I'm not aware of any.

**Comment by davidpdrsn** [comment]
I'll close this issue for now. I'm not sure there is much we can do. Would like to hear from someone who has ideas.
