### ISSUE TITLE
Overlapping routes with differing methods cause a panic in 0.3.0

### ISSUE THREAD

**Issue by dwalker109** [tokio-rs/axum#451]
### Version

axum v0.3.0

### Platform

Darwin Kernel Version 20.3.0 (macOS Big Sur)

### Description

I upgraded to 0.3.0 tonight and now see a panic when running my app: 
`Invalid route: insertion failed due to conflict with previously registered route: /`

This is caused by having both a GET and POST handler handing the same path. For example:

```rust
pub fn routes() -> Router {
    Router::new()
        .route("/", post(create_post))
        .route("/", get(index_get))
}

Router::new()
    .nest("/themes", routes())
```

Both routes were previously reachable in 0.2.*, though they were (naturally) boxed before.

**Comment by kellytk** [comment]
Shouldn't those be a single route?

`Router::new().route("/", post(handler).get(handler))` is what I'm using successfully with 0.3.

**Comment by davidpdrsn** [comment]
Yep @kellytk is right. You have to add the route once with handlers for both methods.

This is necessary with the changes made to routing in 0.3.

**Comment by jplatte** [comment]
From Discord it sounded like it wouldn't be _that_ hard to support this (especially if the pending method router refactoring goes through), so could we re-open this issue for tracking that?

**Comment by davidpdrsn** [comment]
I don't remember talking about it but I don't think it'll be easy. I'm thinking the easiest solution would be if matchit's `Node` provided a way to look up if a route already exists and get its corresponding key. Then once #484 is merged we could probably do some stuff to attempt to merge the method routers if we find one already exists.

cc @ibraheemdev

**Comment by ibraheemdev** [comment]
> I'm thinking the easiest solution would be if matchit's Node provided a way to look up if a route already exists and get its corresponding key.

You can just call `node.at(route).ok().is_some()` (ie: the url path `/foo/:bar` will match the route `/foo/:bar`).

The way I would do this, as I mentioned earlier, is by storing a `HashMap<Method, Node<Service>>` instead of a single `Node<MethodRouter>`:
```rust
app.route("/", get(foo))           => map.get(GET).insert("/", foo)
app.route("/", get(foo).post(bar)) => map.get(GET).insert("/", foo), map.get(POST).insert("/", bar)
```

There wouldn't be any difference between `.route("/", post(handler).get(handler))` and if you registered them both individually, because both just stick the routes in the map.

For `any` routes, you could either store a clone of the service under each method, which would be cheap if services are already `Arc`'d (are they?), and would give you better conflict handling (ie: `.any("/foo", bar).get("/foo", bar)` would conflict instead of making the GET unreachable), or you could have a node that you check first. Giving priority to explicit method routes when there is already an any route registered is doable with the cloning approach, if you want to go that *route*.

(Also a `HashMap` would increase routing performance, not that it matters :wink:)

**Comment by davidpdrsn** [comment]
Added this to the 0.4 milestone because I believe it'll require https://github.com/tokio-rs/axum/pull/484

**Comment by davidpdrsn** [comment]
axum doesn't store its routes as a `Node<Service>` but rather a `Node<RouteId>` plus a `HashMap<RouteId, Service>`. This is necessary because `Router::layer` needs to rebuild the router but point the routes to different services. Not sure that'll matter of this issue but just wanted to clarify that.

**Comment by taikulawo** [comment]
Does there are other solution? I want to use my http_server in handler like this
```rs
let http_server1 = http_server.clone();
    let router = router.route(
        "/http/upstream/:upstream_name",
        get_service(service_fn(move |req: Request| {
            // clone http_server, so we can use in handler
            let server = http_server1.clone();
            async move {
                let res = server.list_upstream(req).await;
                Ok(res)
            }
        })),
    );
    let http_server1 = http_server.clone();
    let router = router.route(
        "/http/upstream/:name",
        delete_service(service_fn(move |req: Request| {
            let server = http_server1.clone();
            async move {
                let res = server.delete_upstream(req).await;
                Ok(res)
            }
        })),
    );
```

But If I nested router in combined, rust complain
![image](https://github.com/user-attachments/assets/2df4bf7d-7161-4592-a4fb-5595aa4fd926)
I cannot clone `http_server` before move into closure

**Comment by jplatte** [comment]
@taikulawo Your question doesn't seem to be related to the (very old) issue that you commented on. Please use the [Q&A section](https://github.com/tokio-rs/axum/discussions/categories/q-a).
