### ISSUE TITLE
Add distributed tracing support

### ISSUE THREAD

**Issue by sergeyshaykhullin** [tokio-rs/axum#546]
## Feature Request
Add support to extract trace ids from request headers and create request scoped span

**Comment by davidpdrsn** [comment]
For collecting high level trace data you can use [`tower_http::trace::Trace`](https://docs.rs/tower-http/0.1.2/tower_http/trace/index.html). We have an example [here](https://github.com/tokio-rs/axum/blob/main/examples/tracing-aka-logging/src/main.rs).

For doing "distributed tracing" (probably with opentelemetry) you can use [tracing-opentelemetry](https://crates.io/crates/tracing-opentelemetry) and some exporter from [opentelemetry](https://github.com/open-telemetry/opentelemetry-rust). Exactly what your setup should be depends on your application. None of that is axum specific though.

We don't plan on building these kinds of things directly into axum at this point.

I'll close this issue since its not actionable but feel free to ask follow up questions!

**Comment by sergeyshaykhullin** [comment]
Hmm... I thought it can be implemented like poem does https://github.com/poem-web/poem/blob/master/poem/src/middleware/opentelemetry_tracing.rs

**Comment by davidpdrsn** [comment]
Yep that looks entirely possible! However you'll have to write it yourself. We don't plan on building this sorta stuff into axum directly.

It should be doable entirely using tower, without anything axum specific. Would make a great crate! Maybe you should write and publish one 😊

**Comment by sergeyshaykhullin** [comment]
Seems like this is the think i need https://github.com/tower-rs/tower-http/pull/180
