### ISSUE TITLE
axum example hello_world  language support

### ISSUE THREAD

**Issue by yxdxx** [tokio-rs/axum#566]
## Bug Report

I tied the hello_world example. I just changed the content of handler. which from english to chinese
async fn handler() -> Html<&'static str> {
    Html("<h1>Hello, World!</h1>")
}

async fn handler() -> Html<&'static str> {
    Html("<h1>你好，世界!</h1>")
}

the Edge browser can't display it correct。
something like ”浣犲ソ锛屼笘鐣�!"

any sloution for that? thanks。

### Version

List the versions of all `axum` crates you are using. The easiest way to get
this information is using `cargo tree`:

`cargo tree | grep axum`
axum version is 0.3.4

### Platform

Output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)
64-bit windows

### Description

I tried this code:

async fn handler() -> Html<&'static str> {
    Html("<h1>你好，世界!</h1>")
}

I expected to see this happen: 你好，世界!

Instead, this happened: 浣犲ソ锛屼笘鐣�!

**Comment by davidpdrsn** [comment]
This was probably fixed by https://github.com/tokio-rs/axum/pull/554. Can you try using the latest main?

Also, plese format your code using triple backticks like shown [here](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks). Makes it much easier to read.
