### ISSUE TITLE
`axum` v0.3.4 Fail to Compile in Recent Hours

### ISSUE THREAD

**Issue by billy1624** [tokio-rs/axum#585]
### Version
```
sea-orm-axum-example v0.1.0 (/sea-orm/examples/axum_example)
├── axum v0.3.4
│   ├── axum-core v0.1.0
```

### Platform
MacOS 21.1.0

### Description
Seems that the upstream dependency of `axum` version `0.3.4` has been updated in these few hours?

It cause the follow project fail to compile
- https://github.com/SeaQL/sea-orm/tree/master/examples/axum_example

**Detail Log**
1. At around "Fri, 03 Dec 2021 05:30 GMT", the axum example can be compiled successfully
    - https://github.com/SeaQL/sea-orm/runs/4404459041
2. However, around "Fri, 03 Dec 2021 08:52 GMT", the example fail to compile for some reason
    - https://github.com/SeaQL/sea-orm/runs/4405871673

I spot something unusual...
- For (1) it didn't download and compile `axum-core v0.1.0`, as you can see [here](https://github.com/SeaQL/sea-orm/runs/4404459041?check_suite_focus=true#step:4:93)
- For (2) it download and compile a new dependency `axum-core v0.1.0`, as you can see [here](https://github.com/SeaQL/sea-orm/runs/4405871673?check_suite_focus=true#step:4:95)

Thanks!!

**Comment by davidpdrsn** [comment]
This is mostly likely because you're depending [`tower-cookies` via a git dependency](https://github.com/SeaQL/sea-orm/blob/master/examples/axum_example/Cargo.toml#L16). It was [recently updated to use axum-core 0.1](https://github.com/imbolc/tower-cookies/pull/5) which requires axum 0.4, which you're not using. So you're running two versions of axum which aren't semver compatible.

**Comment by billy1624** [comment]
Hey @davidpdrsn, thanks for the help and quick response! :P
