### ISSUE TITLE
Only one method of route is accepted.

### ISSUE THREAD

**Issue by songww** [tokio-rs/axum#62]
### Version

0.1.1

### Description

Only last method is accepted when same route path with different methods, other methods returns 404.

I tried this code:

```rust
use axum::prelude::*;
use hyper::server::Server;

async fn index() -> &'static str {
    "Hi"
}

#[tokio::main]
async fn main() {
    let app = route("/", get(index)).route("/", post(index));
    // run it with hyper on localhost:3000
    Server::bind(&"0.0.0.0:3000".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .unwrap();
}
```

I expected to see this happen: request / with get method returns 404.

Instead, this happened: request / with get method returns "hi".

**Comment by davidpdrsn** [comment]
That's an unfortunate side effect of the design of the router. If the path matches, which it does here, it checks the request methods but doesn't fallback to checking the next route. Not sure it's possible to fix with the current design 😕

I'll give it a shot but otherwise we should mention it in the docs.

**Comment by davidpdrsn** [comment]
Routing to multiple methods is done like this:

```rust
let app = route("/", get(index).post(index));
```

**Comment by davidpdrsn** [comment]
I don't think there is a way around with this given the current design of the router. Updating the docs is tracked in https://github.com/tokio-rs/axum/issues/67
