### ISSUE TITLE
[QUESTION]: How to define HTTP workers, e.g. GPU workloads? 

### ISSUE THREAD

**Issue by philschmid** [tokio-rs/axum#692]
Hello 🙋🏻‍♂️, 

I went through all of the documentation about `axum`, and `hyper`, but i couldn't find any information on how to define the "worker" numbers for axum/hyper. 
My question how can someone define the HTTP"workers" (how many simultaneous requests can be handled)? I know you can adjust `tokio`, but I want to use all cores but only a specific amount of HTTP workers, e.g. ML use cases or working with GPUs. 

In `actix-web` you can defined `.workers(n)` when creating the `HttpServer`
```rust
use actix_web::{web, App, HttpResponse, HttpServer};

#[actix_web::main]
async fn main() {
    HttpServer::new(|| {
        App::new().route("/", web::get().to(|| HttpResponse::Ok()))
    })
    .workers(4); // <- Start 4 workers
}
```

**Comment by davidpdrsn** [comment]
How many threads your tokio runtime uses and how many concurrent requests you can handle/will allow, are very different things. I suspect they're also different in actix as well so I don't thinks "workers" here means "how many concurrent requests". Only allowing the same number of concurrent requests as you have CPU cores doesn't sound like a good idea so I doubt thats what actix does. The whole point of async is to allow other things to make progress while you're waiting on IO 😊

As you mention the number of threads used by tokio must be configured when you create the runtime and concurrency can be limited with a middleware. What exactly that middleware will look like depends on whether you want to limit concurrent connections or concurrent requests. You can probably get inspired by https://docs.rs/tower/latest/tower/limit/struct.ConcurrencyLimit.html.

I'll close this since its not specific to axum. Feel free to ask follow up questions.

**Comment by philschmid** [comment]
Wow, thank you for your quick response! I fully agree with what you say!
But 
_"Only allowing the same number of concurrent requests as you have CPU cores doesn't sound like a good idea so I doubt that's what actix does"_
 is actually a common pattern other webframeworks/libraries do, e.g. in Python `uvicorn` -> `fastAPI`, `starlette` etc. Not saying that it is good. 
 My missing point was definitely the `tower` middleware. Since i didn't want to limit the resources more what is happening! Thank you and btw. `actix-web` is doing it
> HttpServer automatically starts a number of HTTP workers, by default this number is equal to the number of logical CPUs in the system. This number can be overridden with the HttpServer::workers() method.
