### ISSUE TITLE
Clarify which crates are necessary to get started

### ISSUE THREAD

**Issue by jcbritobr** [tokio-rs/axum#70]
We need enhance documentation for the examples. There are a lot of dependencies. Its hard to know what is needed to compile, and makes hard to setup a new project as we dont know from what crates this functions come.

**Comment by davidpdrsn** [comment]
For anyone wanting to contribute the crates axum users are most likely to need are

- [axum](https://crates.io/crates/axum). Well duh..
- [tokio](https://crates.io/crates/tokio)
- [hyper](https://crates.io/crates/hyper)
- [tower](https://crates.io/crates/tower). This is mostly necessary for testing to call services.
- [tower-http](https://crates.io/crates/tower-http). For common middleware. Axum re-exports [`AddExtension`](https://docs.rs/tower-http/0.1.1/tower_http/add_extension/struct.AddExtension.html) so if thats all you need you don't need to depend on tower-http.
- [http](https://crates.io/crates/http). For types like `StatusCode`, `HeaderMap`, and other HTTP related types.

The minimal subset of features required for tokio and hyper I'm not sure of. Using `features = ["full"]` in the docs is probably fine.

Axum is quite conservative about re-exporting so its intentional that we don't re-export all these crates. Large numbers of re-exports usually leads to problems.
