### ISSUE TITLE
add `x-requested-with support` to allow_headers please

### ISSUE THREAD

**Issue by 21pages** [tokio-rs/axum#749]
### Motivation
```rust
CorsLayer::new().allow_headers(vec![ORIGIN, CONTENT_TYPE, ACCEPT, AUTHORIZATION]) 
```
when axum work with react and method is POST, sometimes it's header is `Access-Control-Request-Headers: x-requested-with`, but axum doesn't support

### Proposal
add `x-requested-with support` to allow_headers please

**Comment by davidpdrsn** [comment]
See the docs for [`HeaderName`](https://docs.rs/http/0.2.6/http/header/struct.HeaderName.html#method.from_static) for other ways to construct them. You don't have to use the constants.

This should do it:

```rust
CorsLayer::new().allow_headers(vec![axum::http::header::HeaderName::from_static("x-requested-with")]) 
```

You can also do `"some-dynamic-header-name".parse::<HeaderName>().unwrap()` since [`HeaderMap` implements `FromStr`.](https://docs.rs/http/0.2.6/http/header/struct.HeaderName.html#impl-FromStr)

**Comment by davidpdrsn** [comment]
No problem 😊
