### ISSUE TITLE
Make shutdown_signal() Function a One Line Operation

### ISSUE THREAD

**Issue by LeahWhalen** [tokio-rs/axum#907]
### Calling a default shutdown signal function prevents redundant code

Avid lover of axum here, but I think putting the shutdown signal function as a default somewhere would make axum examples look nicer, building servers would be easier, and developers wouldn't have to initialize it every time.

### Proposal

One could easily make some sort of "shutdown signal" struct with a default new and a few customization options.
Here is the shutdown_signal function being referred to:

```
async fn shutdown_signal() {
    let ctrl_c = async {
        signal::ctrl_c()
            .await
            .expect("failed to install Ctrl+C handler");
    };

    #[cfg(unix)]
    let terminate = async {
        signal::unix::signal(signal::unix::SignalKind::terminate())
            .expect("failed to install signal handler")
            .recv()
            .await;
    };

    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();

    tokio::select! {
        _ = ctrl_c => {},
        _ = terminate => {},
    }
    println!("signal received, starting graceful shutdown");
}
```

### Alternatives

An alternative would be to just put the shutdown signal in a callable function somewhere in axum. It doesn't seem like a massive upgrade. I'm willing to help.

**Comment by davidpdrsn** [comment]
Happy to hear you're enjoying axum 😃

Actually axum doesn't know anything about shutdown signals. Its added to `axum::Server` which is a re-export of [`hyper::Server`](https://docs.rs/hyper/latest/hyper/server/struct.Server.html). So only hyper knows about graceful shutdown.

We _could_ add it to axum-extra but it would feel sorta out of place since it would also be useful to people who are using hyper without axum 🤔 So I think it would fit better in something like a hyper-utils crate.

How do you feel about opening an issue on hyper instead?

**Comment by LeahWhalen** [comment]
Yeah, I can do that! Sounds like a good idea.

**Comment by davidpdrsn** [comment]
Thanks! I'll close this for now then.
